coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false
#comment: false
