coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        informational: false
        only_pulls: false
    patch:
      default:
        enabled: false
comment: false
